### ISSUE TITLE
Bug: Attempt to read property "type" on null

### ISSUE THREAD

**Issue by b3nhartl3y** [D3VM4TT/craft-structure-plus#3]
When adding a channel via the link Channel field, when saving I get this error. Happened the first couple of times.

![Screenshot 2024-11-01 at 19 06 43](https://github.com/user-attachments/assets/083949d5-a519-46d2-b1b1-d91f5c2a0b2a)

**Comment by D3VM4TT** [comment]
Hey,

This has been resolve on [commit](https://github.com/D3VM4TT/craft-structure-plus/commit/9fb9e3a956b317deee312d0062301fd878e952c0)

**Comment by D3VM4TT** [comment]
Hey,

This has been resolve on [commit](https://github.com/D3VM4TT/craft-structure-plus/commit/9fb9e3a956b317deee312d0062301fd878e952c0)
