### ISSUE TITLE
Bug - Edit button in entry view.

### ISSUE THREAD

**Issue by ben-honcho** [D3VM4TT/craft-structure-plus#9]
Bug where-by a user can't click on the "Edit" button in the entry view.

Getting unknown property: craft\elements\Entry::customColumn

https://www.loom.com/share/dff457844cc74d2b915188981e57ac71

**Comment by MattDeJager** [comment]
Hey @ben-honcho 

I think this has been resolved.

Please can you test both 4 & 5 branches when you get a chance and close if resolved
